version: '3'

volumes:
  db:
  bundle:

services:
  db:
    image: postgres:12.2
    volumes:
      - 'db:/var/lib/postgresql/data'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  web:
    build: .
    command: bash -c "rm -f test/dummy/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - '.:/app'
      - bundle:/usr/local/bundle
      - ./node_modules:/app/node_modules
    ports:
      - '3002:3000'
    depends_on:
      - db
    stdin_open: true
    tty: true
